// source: schema/cli.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var schema_token_pb = require('../schema/token_pb.js');
goog.object.extend(proto, schema_token_pb);
goog.exportSymbol('proto.cli.Command', null, global);
goog.exportSymbol('proto.cli.Command.DataCase', null, global);
goog.exportSymbol('proto.cli.Command.StoreProject', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cli.Command = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.cli.Command.oneofGroups_);
};
goog.inherits(proto.cli.Command, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cli.Command.displayName = 'proto.cli.Command';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cli.Command.StoreProject = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cli.Command.StoreProject, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cli.Command.StoreProject.displayName = 'proto.cli.Command.StoreProject';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.cli.Command.oneofGroups_ = [[2]];

/**
 * @enum {number}
 */
proto.cli.Command.DataCase = {
  DATA_NOT_SET: 0,
  STOREPROJECT: 2
};

/**
 * @return {proto.cli.Command.DataCase}
 */
proto.cli.Command.prototype.getDataCase = function() {
  return /** @type {proto.cli.Command.DataCase} */(jspb.Message.computeOneofCase(this, proto.cli.Command.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cli.Command.prototype.toObject = function(opt_includeInstance) {
  return proto.cli.Command.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cli.Command} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cli.Command.toObject = function(includeInstance, msg) {
  var f, obj = {
    networkid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    storeproject: (f = msg.getStoreproject()) && proto.cli.Command.StoreProject.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cli.Command}
 */
proto.cli.Command.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cli.Command;
  return proto.cli.Command.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cli.Command} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cli.Command}
 */
proto.cli.Command.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNetworkid(value);
      break;
    case 2:
      var value = new proto.cli.Command.StoreProject;
      reader.readMessage(value,proto.cli.Command.StoreProject.deserializeBinaryFromReader);
      msg.setStoreproject(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cli.Command.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cli.Command.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cli.Command} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cli.Command.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNetworkid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStoreproject();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.cli.Command.StoreProject.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cli.Command.StoreProject.prototype.toObject = function(opt_includeInstance) {
  return proto.cli.Command.StoreProject.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cli.Command.StoreProject} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cli.Command.StoreProject.toObject = function(includeInstance, msg) {
  var f, obj = {
    address: jspb.Message.getFieldWithDefault(msg, 1, ""),
    metadata: (f = msg.getMetadata()) && schema_token_pb.SecurityToken.Metadata.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cli.Command.StoreProject}
 */
proto.cli.Command.StoreProject.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cli.Command.StoreProject;
  return proto.cli.Command.StoreProject.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cli.Command.StoreProject} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cli.Command.StoreProject}
 */
proto.cli.Command.StoreProject.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddress(value);
      break;
    case 2:
      var value = new schema_token_pb.SecurityToken.Metadata;
      reader.readMessage(value,schema_token_pb.SecurityToken.Metadata.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cli.Command.StoreProject.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cli.Command.StoreProject.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cli.Command.StoreProject} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cli.Command.StoreProject.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddress();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      schema_token_pb.SecurityToken.Metadata.serializeBinaryToWriter
    );
  }
};


/**
 * optional string address = 1;
 * @return {string}
 */
proto.cli.Command.StoreProject.prototype.getAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cli.Command.StoreProject} returns this
 */
proto.cli.Command.StoreProject.prototype.setAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional token.SecurityToken.Metadata metadata = 2;
 * @return {?proto.token.SecurityToken.Metadata}
 */
proto.cli.Command.StoreProject.prototype.getMetadata = function() {
  return /** @type{?proto.token.SecurityToken.Metadata} */ (
    jspb.Message.getWrapperField(this, schema_token_pb.SecurityToken.Metadata, 2));
};


/**
 * @param {?proto.token.SecurityToken.Metadata|undefined} value
 * @return {!proto.cli.Command.StoreProject} returns this
*/
proto.cli.Command.StoreProject.prototype.setMetadata = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cli.Command.StoreProject} returns this
 */
proto.cli.Command.StoreProject.prototype.clearMetadata = function() {
  return this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cli.Command.StoreProject.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string networkId = 1;
 * @return {string}
 */
proto.cli.Command.prototype.getNetworkid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cli.Command} returns this
 */
proto.cli.Command.prototype.setNetworkid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional StoreProject storeProject = 2;
 * @return {?proto.cli.Command.StoreProject}
 */
proto.cli.Command.prototype.getStoreproject = function() {
  return /** @type{?proto.cli.Command.StoreProject} */ (
    jspb.Message.getWrapperField(this, proto.cli.Command.StoreProject, 2));
};


/**
 * @param {?proto.cli.Command.StoreProject|undefined} value
 * @return {!proto.cli.Command} returns this
*/
proto.cli.Command.prototype.setStoreproject = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.cli.Command.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cli.Command} returns this
 */
proto.cli.Command.prototype.clearStoreproject = function() {
  return this.setStoreproject(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cli.Command.prototype.hasStoreproject = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.cli);
