// @generated by protoc-gen-es v1.1.1
// @generated from file cmd/v1/cmd.proto (package cmd.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { SecurityToken_Metadata } from "../../token/v1/token_pb.js";

/**
 * @generated from message cmd.v1.Command
 */
export declare class Command extends Message<Command> {
  /**
   * @generated from field: string network_id = 1;
   */
  networkId: string;

  /**
   * @generated from oneof cmd.v1.Command.data
   */
  data: {
    /**
     * @generated from field: cmd.v1.Command.ShareProject share_project = 2;
     */
    value: Command_ShareProject;
    case: "shareProject";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<Command>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cmd.v1.Command";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Command;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Command;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Command;

  static equals(a: Command | PlainMessage<Command> | undefined, b: Command | PlainMessage<Command> | undefined): boolean;
}

/**
 * @generated from message cmd.v1.Command.ShareProject
 */
export declare class Command_ShareProject extends Message<Command_ShareProject> {
  /**
   * @generated from field: string address = 1;
   */
  address: string;

  /**
   * @generated from field: token.v1.SecurityToken.Metadata metadata = 2;
   */
  metadata?: SecurityToken_Metadata;

  constructor(data?: PartialMessage<Command_ShareProject>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "cmd.v1.Command.ShareProject";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Command_ShareProject;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Command_ShareProject;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Command_ShareProject;

  static equals(a: Command_ShareProject | PlainMessage<Command_ShareProject> | undefined, b: Command_ShareProject | PlainMessage<Command_ShareProject> | undefined): boolean;
}

