// @generated by protoc-gen-es v1.1.1
// @generated from file token/v1/token.proto (package token.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Property } from "../../common/v1/common_pb.js";

/**
 * @generated from message token.v1.SecurityToken
 */
export const SecurityToken = proto3.makeMessageType(
  "token.v1.SecurityToken",
  () => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "issuer", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "symbol", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "granularity", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 6, name: "cap", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 7, name: "total_supply", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 10, name: "metadata", kind: "message", T: SecurityToken_Metadata },
  ],
);

/**
 * @generated from message token.v1.SecurityToken.Metadata
 */
export const SecurityToken_Metadata = proto3.makeMessageType(
  "token.v1.SecurityToken.Metadata",
  () => [
    { no: 1, name: "logo", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "SecurityToken_Metadata"},
);

/**
 * @generated from message token.v1.Issuer
 */
export const Issuer = proto3.makeMessageType(
  "token.v1.Issuer",
  () => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "metadata", kind: "message", T: Issuer_Metadata },
  ],
);

/**
 * @generated from message token.v1.Issuer.Metadata
 */
export const Issuer_Metadata = proto3.makeMessageType(
  "token.v1.Issuer.Metadata",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "logo", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "bg_image", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "Issuer_Metadata"},
);

/**
 * @generated from message token.v1.Document
 */
export const Document = proto3.makeMessageType(
  "token.v1.Document",
  () => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "hash", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "metadata", kind: "message", T: Document_Metadata },
  ],
);

/**
 * @generated from message token.v1.Document.Metadata
 */
export const Document_Metadata = proto3.makeMessageType(
  "token.v1.Document.Metadata",
  () => [
    { no: 1, name: "icon", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "Document_Metadata"},
);

/**
 * @generated from message token.v1.Partition
 */
export const Partition = proto3.makeMessageType(
  "token.v1.Partition",
  () => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "id", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 3, name: "modules", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 10, name: "metadata", kind: "message", T: Partition_Metadata },
  ],
);

/**
 * @generated from message token.v1.Partition.Metadata
 */
export const Partition_Metadata = proto3.makeMessageType(
  "token.v1.Partition.Metadata",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "properties", kind: "message", T: Property, repeated: true },
  ],
  {localName: "Partition_Metadata"},
);

