// @generated by protoc-gen-es v1.1.1
// @generated from file module/v1/module.proto (package module.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message module.v1.Module
 */
export const Module = proto3.makeMessageType(
  "module.v1.Module",
  [],
);

