// @generated by protoc-gen-es v1.1.1
// @generated from file account/v1/account.proto (package account.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message account.v1.Account
 */
export declare class Account extends Message<Account> {
  /**
   * @generated from field: string address = 1;
   */
  address: string;

  /**
   * @generated from field: repeated string roles = 2;
   */
  roles: string[];

  /**
   * @generated from field: account.v1.Account.Metadata metadata = 10;
   */
  metadata?: Account_Metadata;

  constructor(data?: PartialMessage<Account>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "account.v1.Account";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Account;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Account;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Account;

  static equals(a: Account | PlainMessage<Account> | undefined, b: Account | PlainMessage<Account> | undefined): boolean;
}

/**
 * @generated from message account.v1.Account.Metadata
 */
export declare class Account_Metadata extends Message<Account_Metadata> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string avatar = 2;
   */
  avatar: string;

  constructor(data?: PartialMessage<Account_Metadata>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "account.v1.Account.Metadata";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Account_Metadata;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Account_Metadata;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Account_Metadata;

  static equals(a: Account_Metadata | PlainMessage<Account_Metadata> | undefined, b: Account_Metadata | PlainMessage<Account_Metadata> | undefined): boolean;
}

