// @generated by protoc-gen-es v1.1.1
// @generated from file account/v1/account.proto (package account.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message account.v1.Account
 */
export const Account = proto3.makeMessageType(
  "account.v1.Account",
  () => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "roles", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 10, name: "metadata", kind: "message", T: Account_Metadata },
  ],
);

/**
 * @generated from message account.v1.Account.Metadata
 */
export const Account_Metadata = proto3.makeMessageType(
  "account.v1.Account.Metadata",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "avatar", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "Account_Metadata"},
);

