// @generated by protoc-gen-es v1.1.1
// @generated from file transaction/v1/transaction.proto (package transaction.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, Duration, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Timestamp } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { SecurityToken_Metadata } from "../../token/v1/token_pb.js";

/**
 * factories/SecurityTokenFactory.sol 
 *
 * @generated from message transaction.v1.Transaction
 */
export declare class Transaction extends Message<Transaction> {
  /**
   * @generated from field: optional transaction.v1.Transaction.Metadata metadata = 1;
   */
  metadata?: Transaction_Metadata;

  /**
   * @generated from field: string contract = 2;
   */
  contract: string;

  /**
   * @generated from field: uint32 network = 3;
   */
  network: number;

  /**
   * @generated from oneof transaction.v1.Transaction.data
   */
  data: {
    /**
     * @generated from field: transaction.v1.Transaction.SecurityTokenFactory.DeployNewSecurityToken deploy_new_security_token = 4;
     */
    value: Transaction_SecurityTokenFactory_DeployNewSecurityToken;
    case: "deployNewSecurityToken";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.SecurityToken.BulkIssueByPartition bulk_issue_by_partition = 5;
     */
    value: Transaction_SecurityToken_BulkIssueByPartition;
    case: "bulkIssueByPartition";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.SecurityToken.SetDocument set_document = 6;
     */
    value: Transaction_SecurityToken_SetDocument;
    case: "setDocument";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.SecurityToken.IssueByPartition issue_by_partition = 7;
     */
    value: Transaction_SecurityToken_IssueByPartition;
    case: "issueByPartition";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.SecurityToken.RedeemByPartition redeem_by_partition = 8;
     */
    value: Transaction_SecurityToken_RedeemByPartition;
    case: "redeemByPartition";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.SecurityToken.OperatorRedeemByPartition operator_redeem_by_partition = 9;
     */
    value: Transaction_SecurityToken_OperatorRedeemByPartition;
    case: "operatorRedeemByPartition";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.SecurityToken.RenounceControl renounce_control = 10;
     */
    value: Transaction_SecurityToken_RenounceControl;
    case: "renounceControl";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.SecurityToken.RenounceIssuance renounce_issuance = 11;
     */
    value: Transaction_SecurityToken_RenounceIssuance;
    case: "renounceIssuance";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.Pausable.Pause pause = 12;
     */
    value: Transaction_Pausable_Pause;
    case: "pause";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.Pausable.Unpause unpause = 13;
     */
    value: Transaction_Pausable_Unpause;
    case: "unpause";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.Ownable.TransferOwnership transfer_ownership = 14;
     */
    value: Transaction_Ownable_TransferOwnership;
    case: "transferOwnership";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.ERC1400Raw.AuthorizeOperator authorize_operator = 15;
     */
    value: Transaction_ERC1400Raw_AuthorizeOperator;
    case: "authorizeOperator";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.ERC1400Raw.RevokeOperator revoke_operator = 16;
     */
    value: Transaction_ERC1400Raw_RevokeOperator;
    case: "revokeOperator";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.ERC1400Partition.TransferByPartition transfer_by_partition = 17;
     */
    value: Transaction_ERC1400Partition_TransferByPartition;
    case: "transferByPartition";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.ERC1400Partition.OperatorTransferByPartition operator_transfer_by_partition = 18;
     */
    value: Transaction_ERC1400Partition_OperatorTransferByPartition;
    case: "operatorTransferByPartition";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.ERC1400Partition.AuthorizeOperatorByPartition authorize_operator_by_partition = 19;
     */
    value: Transaction_ERC1400Partition_AuthorizeOperatorByPartition;
    case: "authorizeOperatorByPartition";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.ERC1400Partition.RevokeOperatorByPartition revoke_operator_by_partition = 20;
     */
    value: Transaction_ERC1400Partition_RevokeOperatorByPartition;
    case: "revokeOperatorByPartition";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.ERC1400Partition.TransferWithData transfer_with_data = 21;
     */
    value: Transaction_ERC1400Partition_TransferWithData;
    case: "transferWithData";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.ERC1400Partition.TransferFromWithData transfer_from_with_data = 22;
     */
    value: Transaction_ERC1400Partition_TransferFromWithData;
    case: "transferFromWithData";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.ERC1400ERC20.Transfer transfer = 23;
     */
    value: Transaction_ERC1400ERC20_Transfer;
    case: "transfer";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.ERC1400ERC20.Approve approve = 24;
     */
    value: Transaction_ERC1400ERC20_Approve;
    case: "approve";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.ERC1400ERC20.TransferFrom transfer_from = 25;
     */
    value: Transaction_ERC1400ERC20_TransferFrom;
    case: "transferFrom";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.ERC1400Capped.SetCap set_cap = 26;
     */
    value: Transaction_ERC1400Capped_SetCap;
    case: "setCap";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.Constrainable.SetModulesByPartition set_modules_by_partition = 27;
     */
    value: Transaction_Constrainable_SetModulesByPartition;
    case: "setModulesByPartition";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.Administrable.AddRole add_role = 28;
     */
    value: Transaction_Administrable_AddRole;
    case: "addRole";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.Administrable.BulkAddRole bulk_add_role = 29;
     */
    value: Transaction_Administrable_BulkAddRole;
    case: "bulkAddRole";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.Administrable.RemoveRole remove_role = 30;
     */
    value: Transaction_Administrable_RemoveRole;
    case: "removeRole";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.Administrable.RenounceRole renounce_role = 31;
     */
    value: Transaction_Administrable_RenounceRole;
    case: "renounceRole";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.SpendingLimitsConstraintModule.DeploySpendingLimitsConstraintModule deploy_spending_limits_constraint_module = 32;
     */
    value: Transaction_SpendingLimitsConstraintModule_DeploySpendingLimitsConstraintModule;
    case: "deploySpendingLimitsConstraintModule";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.SpendingLimitsConstraintModule.AddTimelock add_timelock = 33;
     */
    value: Transaction_SpendingLimitsConstraintModule_AddTimelock;
    case: "addTimelock";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.SpendingLimitsConstraintModule.SetTimelock set_timelock = 34;
     */
    value: Transaction_SpendingLimitsConstraintModule_SetTimelock;
    case: "setTimelock";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.SpendingLimitsConstraintModule.DeleteTimelock delete_timelock = 35;
     */
    value: Transaction_SpendingLimitsConstraintModule_DeleteTimelock;
    case: "deleteTimelock";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.TimeLockConstraintModule.DeployTimeLockConstraintModule deploy_time_lock_constraint_module = 36;
     */
    value: Transaction_TimeLockConstraintModule_DeployTimeLockConstraintModule;
    case: "deployTimeLockConstraintModule";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.TimeLockConstraintModule.EditAmountTimeLock edit_amount_time_lock = 37;
     */
    value: Transaction_TimeLockConstraintModule_EditAmountTimeLock;
    case: "editAmountTimeLock";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.TimeLockConstraintModule.EditAccountTimeLock edit_account_time_lock = 38;
     */
    value: Transaction_TimeLockConstraintModule_EditAccountTimeLock;
    case: "editAccountTimeLock";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.TimeLockConstraintModule.EditTimeLock edit_time_lock = 39;
     */
    value: Transaction_TimeLockConstraintModule_EditTimeLock;
    case: "editTimeLock";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.VestingPeriodConstraintModule.DeployVestingPeriodConstraintModule deploy_vesting_period_constraint_module = 40;
     */
    value: Transaction_VestingPeriodConstraintModule_DeployVestingPeriodConstraintModule;
    case: "deployVestingPeriodConstraintModule";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.VestingPeriodConstraintModule.SetVestingOptions set_vesting_options = 41;
     */
    value: Transaction_VestingPeriodConstraintModule_SetVestingOptions;
    case: "setVestingOptions";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.WhitelistConstraintModule.DeployWhitelistConstraintModule deploy_whitelist_constraint_module = 42;
     */
    value: Transaction_WhitelistConstraintModule_DeployWhitelistConstraintModule;
    case: "deployWhitelistConstraintModule";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.WhitelistConstraintModule.EditWhitelist edit_whitelist = 43;
     */
    value: Transaction_WhitelistConstraintModule_EditWhitelist;
    case: "editWhitelist";
  } | {
    /**
     * @generated from field: transaction.v1.Transaction.WhitelistConstraintModule.BulkEditWhitelist bulk_edit_whitelist = 44;
     */
    value: Transaction_WhitelistConstraintModule_BulkEditWhitelist;
    case: "bulkEditWhitelist";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<Transaction>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction;

  static equals(a: Transaction | PlainMessage<Transaction> | undefined, b: Transaction | PlainMessage<Transaction> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.SecurityTokenFactory
 */
export declare class Transaction_SecurityTokenFactory extends Message<Transaction_SecurityTokenFactory> {
  constructor(data?: PartialMessage<Transaction_SecurityTokenFactory>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.SecurityTokenFactory";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_SecurityTokenFactory;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_SecurityTokenFactory;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_SecurityTokenFactory;

  static equals(a: Transaction_SecurityTokenFactory | PlainMessage<Transaction_SecurityTokenFactory> | undefined, b: Transaction_SecurityTokenFactory | PlainMessage<Transaction_SecurityTokenFactory> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.SecurityTokenFactory.DeployNewSecurityToken
 */
export declare class Transaction_SecurityTokenFactory_DeployNewSecurityToken extends Message<Transaction_SecurityTokenFactory_DeployNewSecurityToken> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string symbol = 2;
   */
  symbol: string;

  /**
   * @generated from field: uint64 granularity = 3;
   */
  granularity: bigint;

  /**
   * @generated from field: uint64 cap = 4;
   */
  cap: bigint;

  /**
   * @generated from field: string admin = 5;
   */
  admin: string;

  /**
   * @generated from field: string controller = 6;
   */
  controller: string;

  /**
   * @generated from field: string issuer = 7;
   */
  issuer: string;

  /**
   * @generated from field: string redeemer = 8;
   */
  redeemer: string;

  /**
   * @generated from field: string module_editor = 9;
   */
  moduleEditor: string;

  /**
   * @generated from field: token.v1.SecurityToken.Metadata metadata = 10;
   */
  metadata?: SecurityToken_Metadata;

  constructor(data?: PartialMessage<Transaction_SecurityTokenFactory_DeployNewSecurityToken>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.SecurityTokenFactory.DeployNewSecurityToken";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_SecurityTokenFactory_DeployNewSecurityToken;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_SecurityTokenFactory_DeployNewSecurityToken;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_SecurityTokenFactory_DeployNewSecurityToken;

  static equals(a: Transaction_SecurityTokenFactory_DeployNewSecurityToken | PlainMessage<Transaction_SecurityTokenFactory_DeployNewSecurityToken> | undefined, b: Transaction_SecurityTokenFactory_DeployNewSecurityToken | PlainMessage<Transaction_SecurityTokenFactory_DeployNewSecurityToken> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.SecurityToken
 */
export declare class Transaction_SecurityToken extends Message<Transaction_SecurityToken> {
  constructor(data?: PartialMessage<Transaction_SecurityToken>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.SecurityToken";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_SecurityToken;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_SecurityToken;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_SecurityToken;

  static equals(a: Transaction_SecurityToken | PlainMessage<Transaction_SecurityToken> | undefined, b: Transaction_SecurityToken | PlainMessage<Transaction_SecurityToken> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.SecurityToken.BulkIssueByPartition
 */
export declare class Transaction_SecurityToken_BulkIssueByPartition extends Message<Transaction_SecurityToken_BulkIssueByPartition> {
  /**
   * @generated from field: bytes partition = 1;
   */
  partition: Uint8Array;

  /**
   * @generated from field: repeated string token_holders = 2;
   */
  tokenHolders: string[];

  /**
   * @generated from field: repeated uint64 values = 3;
   */
  values: bigint[];

  /**
   * @generated from field: bytes data = 4;
   */
  data: Uint8Array;

  constructor(data?: PartialMessage<Transaction_SecurityToken_BulkIssueByPartition>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.SecurityToken.BulkIssueByPartition";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_SecurityToken_BulkIssueByPartition;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_SecurityToken_BulkIssueByPartition;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_SecurityToken_BulkIssueByPartition;

  static equals(a: Transaction_SecurityToken_BulkIssueByPartition | PlainMessage<Transaction_SecurityToken_BulkIssueByPartition> | undefined, b: Transaction_SecurityToken_BulkIssueByPartition | PlainMessage<Transaction_SecurityToken_BulkIssueByPartition> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.SecurityToken.SetDocument
 */
export declare class Transaction_SecurityToken_SetDocument extends Message<Transaction_SecurityToken_SetDocument> {
  /**
   * @generated from field: bytes document_name = 1;
   */
  documentName: Uint8Array;

  /**
   * @generated from field: string uri = 2;
   */
  uri: string;

  /**
   * @generated from field: bytes document_hash = 3;
   */
  documentHash: Uint8Array;

  constructor(data?: PartialMessage<Transaction_SecurityToken_SetDocument>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.SecurityToken.SetDocument";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_SecurityToken_SetDocument;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_SecurityToken_SetDocument;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_SecurityToken_SetDocument;

  static equals(a: Transaction_SecurityToken_SetDocument | PlainMessage<Transaction_SecurityToken_SetDocument> | undefined, b: Transaction_SecurityToken_SetDocument | PlainMessage<Transaction_SecurityToken_SetDocument> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.SecurityToken.IssueByPartition
 */
export declare class Transaction_SecurityToken_IssueByPartition extends Message<Transaction_SecurityToken_IssueByPartition> {
  /**
   * @generated from field: bytes partition = 1;
   */
  partition: Uint8Array;

  /**
   * @generated from field: string recipient = 2;
   */
  recipient: string;

  /**
   * @generated from field: uint64 amount = 3;
   */
  amount: bigint;

  constructor(data?: PartialMessage<Transaction_SecurityToken_IssueByPartition>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.SecurityToken.IssueByPartition";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_SecurityToken_IssueByPartition;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_SecurityToken_IssueByPartition;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_SecurityToken_IssueByPartition;

  static equals(a: Transaction_SecurityToken_IssueByPartition | PlainMessage<Transaction_SecurityToken_IssueByPartition> | undefined, b: Transaction_SecurityToken_IssueByPartition | PlainMessage<Transaction_SecurityToken_IssueByPartition> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.SecurityToken.RedeemByPartition
 */
export declare class Transaction_SecurityToken_RedeemByPartition extends Message<Transaction_SecurityToken_RedeemByPartition> {
  /**
   * @generated from field: bytes partition = 1;
   */
  partition: Uint8Array;

  /**
   * @generated from field: uint64 value = 2;
   */
  value: bigint;

  /**
   * @generated from field: bytes data = 3;
   */
  data: Uint8Array;

  constructor(data?: PartialMessage<Transaction_SecurityToken_RedeemByPartition>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.SecurityToken.RedeemByPartition";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_SecurityToken_RedeemByPartition;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_SecurityToken_RedeemByPartition;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_SecurityToken_RedeemByPartition;

  static equals(a: Transaction_SecurityToken_RedeemByPartition | PlainMessage<Transaction_SecurityToken_RedeemByPartition> | undefined, b: Transaction_SecurityToken_RedeemByPartition | PlainMessage<Transaction_SecurityToken_RedeemByPartition> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.SecurityToken.OperatorRedeemByPartition
 */
export declare class Transaction_SecurityToken_OperatorRedeemByPartition extends Message<Transaction_SecurityToken_OperatorRedeemByPartition> {
  /**
   * @generated from field: bytes partition = 1;
   */
  partition: Uint8Array;

  /**
   * @generated from field: string token_holder = 2;
   */
  tokenHolder: string;

  /**
   * @generated from field: uint64 value = 3;
   */
  value: bigint;

  /**
   * @generated from field: bytes data = 4;
   */
  data: Uint8Array;

  /**
   * @generated from field: bytes operator_data = 5;
   */
  operatorData: Uint8Array;

  constructor(data?: PartialMessage<Transaction_SecurityToken_OperatorRedeemByPartition>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.SecurityToken.OperatorRedeemByPartition";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_SecurityToken_OperatorRedeemByPartition;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_SecurityToken_OperatorRedeemByPartition;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_SecurityToken_OperatorRedeemByPartition;

  static equals(a: Transaction_SecurityToken_OperatorRedeemByPartition | PlainMessage<Transaction_SecurityToken_OperatorRedeemByPartition> | undefined, b: Transaction_SecurityToken_OperatorRedeemByPartition | PlainMessage<Transaction_SecurityToken_OperatorRedeemByPartition> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.SecurityToken.RenounceControl
 */
export declare class Transaction_SecurityToken_RenounceControl extends Message<Transaction_SecurityToken_RenounceControl> {
  constructor(data?: PartialMessage<Transaction_SecurityToken_RenounceControl>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.SecurityToken.RenounceControl";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_SecurityToken_RenounceControl;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_SecurityToken_RenounceControl;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_SecurityToken_RenounceControl;

  static equals(a: Transaction_SecurityToken_RenounceControl | PlainMessage<Transaction_SecurityToken_RenounceControl> | undefined, b: Transaction_SecurityToken_RenounceControl | PlainMessage<Transaction_SecurityToken_RenounceControl> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.SecurityToken.RenounceIssuance
 */
export declare class Transaction_SecurityToken_RenounceIssuance extends Message<Transaction_SecurityToken_RenounceIssuance> {
  constructor(data?: PartialMessage<Transaction_SecurityToken_RenounceIssuance>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.SecurityToken.RenounceIssuance";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_SecurityToken_RenounceIssuance;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_SecurityToken_RenounceIssuance;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_SecurityToken_RenounceIssuance;

  static equals(a: Transaction_SecurityToken_RenounceIssuance | PlainMessage<Transaction_SecurityToken_RenounceIssuance> | undefined, b: Transaction_SecurityToken_RenounceIssuance | PlainMessage<Transaction_SecurityToken_RenounceIssuance> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.Pausable
 */
export declare class Transaction_Pausable extends Message<Transaction_Pausable> {
  constructor(data?: PartialMessage<Transaction_Pausable>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.Pausable";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_Pausable;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_Pausable;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_Pausable;

  static equals(a: Transaction_Pausable | PlainMessage<Transaction_Pausable> | undefined, b: Transaction_Pausable | PlainMessage<Transaction_Pausable> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.Pausable.Pause
 */
export declare class Transaction_Pausable_Pause extends Message<Transaction_Pausable_Pause> {
  constructor(data?: PartialMessage<Transaction_Pausable_Pause>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.Pausable.Pause";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_Pausable_Pause;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_Pausable_Pause;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_Pausable_Pause;

  static equals(a: Transaction_Pausable_Pause | PlainMessage<Transaction_Pausable_Pause> | undefined, b: Transaction_Pausable_Pause | PlainMessage<Transaction_Pausable_Pause> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.Pausable.Unpause
 */
export declare class Transaction_Pausable_Unpause extends Message<Transaction_Pausable_Unpause> {
  constructor(data?: PartialMessage<Transaction_Pausable_Unpause>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.Pausable.Unpause";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_Pausable_Unpause;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_Pausable_Unpause;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_Pausable_Unpause;

  static equals(a: Transaction_Pausable_Unpause | PlainMessage<Transaction_Pausable_Unpause> | undefined, b: Transaction_Pausable_Unpause | PlainMessage<Transaction_Pausable_Unpause> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.Ownable
 */
export declare class Transaction_Ownable extends Message<Transaction_Ownable> {
  constructor(data?: PartialMessage<Transaction_Ownable>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.Ownable";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_Ownable;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_Ownable;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_Ownable;

  static equals(a: Transaction_Ownable | PlainMessage<Transaction_Ownable> | undefined, b: Transaction_Ownable | PlainMessage<Transaction_Ownable> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.Ownable.TransferOwnership
 */
export declare class Transaction_Ownable_TransferOwnership extends Message<Transaction_Ownable_TransferOwnership> {
  /**
   * @generated from field: string new_owner = 1;
   */
  newOwner: string;

  constructor(data?: PartialMessage<Transaction_Ownable_TransferOwnership>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.Ownable.TransferOwnership";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_Ownable_TransferOwnership;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_Ownable_TransferOwnership;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_Ownable_TransferOwnership;

  static equals(a: Transaction_Ownable_TransferOwnership | PlainMessage<Transaction_Ownable_TransferOwnership> | undefined, b: Transaction_Ownable_TransferOwnership | PlainMessage<Transaction_Ownable_TransferOwnership> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.ERC1400Raw
 */
export declare class Transaction_ERC1400Raw extends Message<Transaction_ERC1400Raw> {
  constructor(data?: PartialMessage<Transaction_ERC1400Raw>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.ERC1400Raw";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_ERC1400Raw;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_ERC1400Raw;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_ERC1400Raw;

  static equals(a: Transaction_ERC1400Raw | PlainMessage<Transaction_ERC1400Raw> | undefined, b: Transaction_ERC1400Raw | PlainMessage<Transaction_ERC1400Raw> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.ERC1400Raw.AuthorizeOperator
 */
export declare class Transaction_ERC1400Raw_AuthorizeOperator extends Message<Transaction_ERC1400Raw_AuthorizeOperator> {
  /**
   * @generated from field: string operator = 1;
   */
  operator: string;

  constructor(data?: PartialMessage<Transaction_ERC1400Raw_AuthorizeOperator>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.ERC1400Raw.AuthorizeOperator";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_ERC1400Raw_AuthorizeOperator;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_ERC1400Raw_AuthorizeOperator;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_ERC1400Raw_AuthorizeOperator;

  static equals(a: Transaction_ERC1400Raw_AuthorizeOperator | PlainMessage<Transaction_ERC1400Raw_AuthorizeOperator> | undefined, b: Transaction_ERC1400Raw_AuthorizeOperator | PlainMessage<Transaction_ERC1400Raw_AuthorizeOperator> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.ERC1400Raw.RevokeOperator
 */
export declare class Transaction_ERC1400Raw_RevokeOperator extends Message<Transaction_ERC1400Raw_RevokeOperator> {
  /**
   * @generated from field: string operator = 1;
   */
  operator: string;

  constructor(data?: PartialMessage<Transaction_ERC1400Raw_RevokeOperator>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.ERC1400Raw.RevokeOperator";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_ERC1400Raw_RevokeOperator;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_ERC1400Raw_RevokeOperator;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_ERC1400Raw_RevokeOperator;

  static equals(a: Transaction_ERC1400Raw_RevokeOperator | PlainMessage<Transaction_ERC1400Raw_RevokeOperator> | undefined, b: Transaction_ERC1400Raw_RevokeOperator | PlainMessage<Transaction_ERC1400Raw_RevokeOperator> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.ERC1400Partition
 */
export declare class Transaction_ERC1400Partition extends Message<Transaction_ERC1400Partition> {
  constructor(data?: PartialMessage<Transaction_ERC1400Partition>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.ERC1400Partition";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_ERC1400Partition;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_ERC1400Partition;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_ERC1400Partition;

  static equals(a: Transaction_ERC1400Partition | PlainMessage<Transaction_ERC1400Partition> | undefined, b: Transaction_ERC1400Partition | PlainMessage<Transaction_ERC1400Partition> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.ERC1400Partition.TransferByPartition
 */
export declare class Transaction_ERC1400Partition_TransferByPartition extends Message<Transaction_ERC1400Partition_TransferByPartition> {
  /**
   * @generated from field: bytes partition = 1;
   */
  partition: Uint8Array;

  /**
   * @generated from field: string to = 2;
   */
  to: string;

  /**
   * @generated from field: uint64 value = 3;
   */
  value: bigint;

  /**
   * @generated from field: bytes calldata = 4;
   */
  calldata: Uint8Array;

  constructor(data?: PartialMessage<Transaction_ERC1400Partition_TransferByPartition>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.ERC1400Partition.TransferByPartition";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_ERC1400Partition_TransferByPartition;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_ERC1400Partition_TransferByPartition;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_ERC1400Partition_TransferByPartition;

  static equals(a: Transaction_ERC1400Partition_TransferByPartition | PlainMessage<Transaction_ERC1400Partition_TransferByPartition> | undefined, b: Transaction_ERC1400Partition_TransferByPartition | PlainMessage<Transaction_ERC1400Partition_TransferByPartition> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.ERC1400Partition.OperatorTransferByPartition
 */
export declare class Transaction_ERC1400Partition_OperatorTransferByPartition extends Message<Transaction_ERC1400Partition_OperatorTransferByPartition> {
  /**
   * @generated from field: bytes partition = 1;
   */
  partition: Uint8Array;

  /**
   * @generated from field: string from = 2;
   */
  from: string;

  /**
   * @generated from field: string to = 3;
   */
  to: string;

  /**
   * @generated from field: uint64 value = 4;
   */
  value: bigint;

  /**
   * @generated from field: bytes data = 5;
   */
  data: Uint8Array;

  /**
   * @generated from field: bytes operator_data = 6;
   */
  operatorData: Uint8Array;

  constructor(data?: PartialMessage<Transaction_ERC1400Partition_OperatorTransferByPartition>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.ERC1400Partition.OperatorTransferByPartition";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_ERC1400Partition_OperatorTransferByPartition;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_ERC1400Partition_OperatorTransferByPartition;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_ERC1400Partition_OperatorTransferByPartition;

  static equals(a: Transaction_ERC1400Partition_OperatorTransferByPartition | PlainMessage<Transaction_ERC1400Partition_OperatorTransferByPartition> | undefined, b: Transaction_ERC1400Partition_OperatorTransferByPartition | PlainMessage<Transaction_ERC1400Partition_OperatorTransferByPartition> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.ERC1400Partition.AuthorizeOperatorByPartition
 */
export declare class Transaction_ERC1400Partition_AuthorizeOperatorByPartition extends Message<Transaction_ERC1400Partition_AuthorizeOperatorByPartition> {
  /**
   * @generated from field: bytes partition = 1;
   */
  partition: Uint8Array;

  /**
   * @generated from field: string operator = 2;
   */
  operator: string;

  constructor(data?: PartialMessage<Transaction_ERC1400Partition_AuthorizeOperatorByPartition>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.ERC1400Partition.AuthorizeOperatorByPartition";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_ERC1400Partition_AuthorizeOperatorByPartition;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_ERC1400Partition_AuthorizeOperatorByPartition;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_ERC1400Partition_AuthorizeOperatorByPartition;

  static equals(a: Transaction_ERC1400Partition_AuthorizeOperatorByPartition | PlainMessage<Transaction_ERC1400Partition_AuthorizeOperatorByPartition> | undefined, b: Transaction_ERC1400Partition_AuthorizeOperatorByPartition | PlainMessage<Transaction_ERC1400Partition_AuthorizeOperatorByPartition> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.ERC1400Partition.RevokeOperatorByPartition
 */
export declare class Transaction_ERC1400Partition_RevokeOperatorByPartition extends Message<Transaction_ERC1400Partition_RevokeOperatorByPartition> {
  /**
   * @generated from field: bytes partition = 1;
   */
  partition: Uint8Array;

  /**
   * @generated from field: string operator = 2;
   */
  operator: string;

  constructor(data?: PartialMessage<Transaction_ERC1400Partition_RevokeOperatorByPartition>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.ERC1400Partition.RevokeOperatorByPartition";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_ERC1400Partition_RevokeOperatorByPartition;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_ERC1400Partition_RevokeOperatorByPartition;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_ERC1400Partition_RevokeOperatorByPartition;

  static equals(a: Transaction_ERC1400Partition_RevokeOperatorByPartition | PlainMessage<Transaction_ERC1400Partition_RevokeOperatorByPartition> | undefined, b: Transaction_ERC1400Partition_RevokeOperatorByPartition | PlainMessage<Transaction_ERC1400Partition_RevokeOperatorByPartition> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.ERC1400Partition.TransferWithData
 */
export declare class Transaction_ERC1400Partition_TransferWithData extends Message<Transaction_ERC1400Partition_TransferWithData> {
  /**
   * @generated from field: string to = 1;
   */
  to: string;

  /**
   * @generated from field: uint64 value = 2;
   */
  value: bigint;

  /**
   * @generated from field: bytes data = 3;
   */
  data: Uint8Array;

  constructor(data?: PartialMessage<Transaction_ERC1400Partition_TransferWithData>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.ERC1400Partition.TransferWithData";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_ERC1400Partition_TransferWithData;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_ERC1400Partition_TransferWithData;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_ERC1400Partition_TransferWithData;

  static equals(a: Transaction_ERC1400Partition_TransferWithData | PlainMessage<Transaction_ERC1400Partition_TransferWithData> | undefined, b: Transaction_ERC1400Partition_TransferWithData | PlainMessage<Transaction_ERC1400Partition_TransferWithData> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.ERC1400Partition.TransferFromWithData
 */
export declare class Transaction_ERC1400Partition_TransferFromWithData extends Message<Transaction_ERC1400Partition_TransferFromWithData> {
  /**
   * @generated from field: string from = 1;
   */
  from: string;

  /**
   * @generated from field: string to = 2;
   */
  to: string;

  /**
   * @generated from field: uint64 value = 3;
   */
  value: bigint;

  /**
   * @generated from field: bytes data = 4;
   */
  data: Uint8Array;

  /**
   * @generated from field: bytes operator_data = 5;
   */
  operatorData: Uint8Array;

  constructor(data?: PartialMessage<Transaction_ERC1400Partition_TransferFromWithData>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.ERC1400Partition.TransferFromWithData";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_ERC1400Partition_TransferFromWithData;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_ERC1400Partition_TransferFromWithData;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_ERC1400Partition_TransferFromWithData;

  static equals(a: Transaction_ERC1400Partition_TransferFromWithData | PlainMessage<Transaction_ERC1400Partition_TransferFromWithData> | undefined, b: Transaction_ERC1400Partition_TransferFromWithData | PlainMessage<Transaction_ERC1400Partition_TransferFromWithData> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.ERC1400ERC20
 */
export declare class Transaction_ERC1400ERC20 extends Message<Transaction_ERC1400ERC20> {
  constructor(data?: PartialMessage<Transaction_ERC1400ERC20>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.ERC1400ERC20";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_ERC1400ERC20;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_ERC1400ERC20;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_ERC1400ERC20;

  static equals(a: Transaction_ERC1400ERC20 | PlainMessage<Transaction_ERC1400ERC20> | undefined, b: Transaction_ERC1400ERC20 | PlainMessage<Transaction_ERC1400ERC20> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.ERC1400ERC20.Transfer
 */
export declare class Transaction_ERC1400ERC20_Transfer extends Message<Transaction_ERC1400ERC20_Transfer> {
  /**
   * @generated from field: string to = 1;
   */
  to: string;

  /**
   * @generated from field: uint64 value = 2;
   */
  value: bigint;

  constructor(data?: PartialMessage<Transaction_ERC1400ERC20_Transfer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.ERC1400ERC20.Transfer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_ERC1400ERC20_Transfer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_ERC1400ERC20_Transfer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_ERC1400ERC20_Transfer;

  static equals(a: Transaction_ERC1400ERC20_Transfer | PlainMessage<Transaction_ERC1400ERC20_Transfer> | undefined, b: Transaction_ERC1400ERC20_Transfer | PlainMessage<Transaction_ERC1400ERC20_Transfer> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.ERC1400ERC20.Approve
 */
export declare class Transaction_ERC1400ERC20_Approve extends Message<Transaction_ERC1400ERC20_Approve> {
  /**
   * @generated from field: string spender = 1;
   */
  spender: string;

  /**
   * @generated from field: uint64 value = 2;
   */
  value: bigint;

  constructor(data?: PartialMessage<Transaction_ERC1400ERC20_Approve>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.ERC1400ERC20.Approve";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_ERC1400ERC20_Approve;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_ERC1400ERC20_Approve;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_ERC1400ERC20_Approve;

  static equals(a: Transaction_ERC1400ERC20_Approve | PlainMessage<Transaction_ERC1400ERC20_Approve> | undefined, b: Transaction_ERC1400ERC20_Approve | PlainMessage<Transaction_ERC1400ERC20_Approve> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.ERC1400ERC20.TransferFrom
 */
export declare class Transaction_ERC1400ERC20_TransferFrom extends Message<Transaction_ERC1400ERC20_TransferFrom> {
  /**
   * @generated from field: string from = 1;
   */
  from: string;

  /**
   * @generated from field: string to = 2;
   */
  to: string;

  /**
   * @generated from field: uint64 value = 3;
   */
  value: bigint;

  constructor(data?: PartialMessage<Transaction_ERC1400ERC20_TransferFrom>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.ERC1400ERC20.TransferFrom";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_ERC1400ERC20_TransferFrom;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_ERC1400ERC20_TransferFrom;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_ERC1400ERC20_TransferFrom;

  static equals(a: Transaction_ERC1400ERC20_TransferFrom | PlainMessage<Transaction_ERC1400ERC20_TransferFrom> | undefined, b: Transaction_ERC1400ERC20_TransferFrom | PlainMessage<Transaction_ERC1400ERC20_TransferFrom> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.ERC1400Capped
 */
export declare class Transaction_ERC1400Capped extends Message<Transaction_ERC1400Capped> {
  constructor(data?: PartialMessage<Transaction_ERC1400Capped>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.ERC1400Capped";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_ERC1400Capped;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_ERC1400Capped;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_ERC1400Capped;

  static equals(a: Transaction_ERC1400Capped | PlainMessage<Transaction_ERC1400Capped> | undefined, b: Transaction_ERC1400Capped | PlainMessage<Transaction_ERC1400Capped> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.ERC1400Capped.SetCap
 */
export declare class Transaction_ERC1400Capped_SetCap extends Message<Transaction_ERC1400Capped_SetCap> {
  /**
   * @generated from field: uint64 new_cap = 1;
   */
  newCap: bigint;

  constructor(data?: PartialMessage<Transaction_ERC1400Capped_SetCap>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.ERC1400Capped.SetCap";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_ERC1400Capped_SetCap;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_ERC1400Capped_SetCap;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_ERC1400Capped_SetCap;

  static equals(a: Transaction_ERC1400Capped_SetCap | PlainMessage<Transaction_ERC1400Capped_SetCap> | undefined, b: Transaction_ERC1400Capped_SetCap | PlainMessage<Transaction_ERC1400Capped_SetCap> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.Constrainable
 */
export declare class Transaction_Constrainable extends Message<Transaction_Constrainable> {
  constructor(data?: PartialMessage<Transaction_Constrainable>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.Constrainable";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_Constrainable;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_Constrainable;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_Constrainable;

  static equals(a: Transaction_Constrainable | PlainMessage<Transaction_Constrainable> | undefined, b: Transaction_Constrainable | PlainMessage<Transaction_Constrainable> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.Constrainable.SetModulesByPartition
 */
export declare class Transaction_Constrainable_SetModulesByPartition extends Message<Transaction_Constrainable_SetModulesByPartition> {
  /**
   * @generated from field: bytes partition = 1;
   */
  partition: Uint8Array;

  /**
   * @generated from field: repeated string new_modules = 2;
   */
  newModules: string[];

  constructor(data?: PartialMessage<Transaction_Constrainable_SetModulesByPartition>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.Constrainable.SetModulesByPartition";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_Constrainable_SetModulesByPartition;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_Constrainable_SetModulesByPartition;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_Constrainable_SetModulesByPartition;

  static equals(a: Transaction_Constrainable_SetModulesByPartition | PlainMessage<Transaction_Constrainable_SetModulesByPartition> | undefined, b: Transaction_Constrainable_SetModulesByPartition | PlainMessage<Transaction_Constrainable_SetModulesByPartition> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.Administrable
 */
export declare class Transaction_Administrable extends Message<Transaction_Administrable> {
  constructor(data?: PartialMessage<Transaction_Administrable>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.Administrable";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_Administrable;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_Administrable;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_Administrable;

  static equals(a: Transaction_Administrable | PlainMessage<Transaction_Administrable> | undefined, b: Transaction_Administrable | PlainMessage<Transaction_Administrable> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.Administrable.AddRole
 */
export declare class Transaction_Administrable_AddRole extends Message<Transaction_Administrable_AddRole> {
  /**
   * @generated from field: bytes role = 1;
   */
  role: Uint8Array;

  /**
   * @generated from field: string account = 2;
   */
  account: string;

  constructor(data?: PartialMessage<Transaction_Administrable_AddRole>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.Administrable.AddRole";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_Administrable_AddRole;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_Administrable_AddRole;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_Administrable_AddRole;

  static equals(a: Transaction_Administrable_AddRole | PlainMessage<Transaction_Administrable_AddRole> | undefined, b: Transaction_Administrable_AddRole | PlainMessage<Transaction_Administrable_AddRole> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.Administrable.BulkAddRole
 */
export declare class Transaction_Administrable_BulkAddRole extends Message<Transaction_Administrable_BulkAddRole> {
  /**
   * @generated from field: repeated bytes roles = 1;
   */
  roles: Uint8Array[];

  /**
   * @generated from field: repeated string accounts = 2;
   */
  accounts: string[];

  constructor(data?: PartialMessage<Transaction_Administrable_BulkAddRole>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.Administrable.BulkAddRole";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_Administrable_BulkAddRole;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_Administrable_BulkAddRole;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_Administrable_BulkAddRole;

  static equals(a: Transaction_Administrable_BulkAddRole | PlainMessage<Transaction_Administrable_BulkAddRole> | undefined, b: Transaction_Administrable_BulkAddRole | PlainMessage<Transaction_Administrable_BulkAddRole> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.Administrable.RemoveRole
 */
export declare class Transaction_Administrable_RemoveRole extends Message<Transaction_Administrable_RemoveRole> {
  /**
   * @generated from field: bytes role = 1;
   */
  role: Uint8Array;

  /**
   * @generated from field: string account = 2;
   */
  account: string;

  constructor(data?: PartialMessage<Transaction_Administrable_RemoveRole>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.Administrable.RemoveRole";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_Administrable_RemoveRole;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_Administrable_RemoveRole;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_Administrable_RemoveRole;

  static equals(a: Transaction_Administrable_RemoveRole | PlainMessage<Transaction_Administrable_RemoveRole> | undefined, b: Transaction_Administrable_RemoveRole | PlainMessage<Transaction_Administrable_RemoveRole> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.Administrable.RenounceRole
 */
export declare class Transaction_Administrable_RenounceRole extends Message<Transaction_Administrable_RenounceRole> {
  /**
   * @generated from field: bytes role = 1;
   */
  role: Uint8Array;

  constructor(data?: PartialMessage<Transaction_Administrable_RenounceRole>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.Administrable.RenounceRole";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_Administrable_RenounceRole;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_Administrable_RenounceRole;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_Administrable_RenounceRole;

  static equals(a: Transaction_Administrable_RenounceRole | PlainMessage<Transaction_Administrable_RenounceRole> | undefined, b: Transaction_Administrable_RenounceRole | PlainMessage<Transaction_Administrable_RenounceRole> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.SpendingLimitsConstraintModule
 */
export declare class Transaction_SpendingLimitsConstraintModule extends Message<Transaction_SpendingLimitsConstraintModule> {
  constructor(data?: PartialMessage<Transaction_SpendingLimitsConstraintModule>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.SpendingLimitsConstraintModule";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_SpendingLimitsConstraintModule;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_SpendingLimitsConstraintModule;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_SpendingLimitsConstraintModule;

  static equals(a: Transaction_SpendingLimitsConstraintModule | PlainMessage<Transaction_SpendingLimitsConstraintModule> | undefined, b: Transaction_SpendingLimitsConstraintModule | PlainMessage<Transaction_SpendingLimitsConstraintModule> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.SpendingLimitsConstraintModule.DeploySpendingLimitsConstraintModule
 */
export declare class Transaction_SpendingLimitsConstraintModule_DeploySpendingLimitsConstraintModule extends Message<Transaction_SpendingLimitsConstraintModule_DeploySpendingLimitsConstraintModule> {
  /**
   * @generated from field: string token_address = 1;
   */
  tokenAddress: string;

  constructor(data?: PartialMessage<Transaction_SpendingLimitsConstraintModule_DeploySpendingLimitsConstraintModule>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.SpendingLimitsConstraintModule.DeploySpendingLimitsConstraintModule";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_SpendingLimitsConstraintModule_DeploySpendingLimitsConstraintModule;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_SpendingLimitsConstraintModule_DeploySpendingLimitsConstraintModule;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_SpendingLimitsConstraintModule_DeploySpendingLimitsConstraintModule;

  static equals(a: Transaction_SpendingLimitsConstraintModule_DeploySpendingLimitsConstraintModule | PlainMessage<Transaction_SpendingLimitsConstraintModule_DeploySpendingLimitsConstraintModule> | undefined, b: Transaction_SpendingLimitsConstraintModule_DeploySpendingLimitsConstraintModule | PlainMessage<Transaction_SpendingLimitsConstraintModule_DeploySpendingLimitsConstraintModule> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.SpendingLimitsConstraintModule.AddTimelock
 */
export declare class Transaction_SpendingLimitsConstraintModule_AddTimelock extends Message<Transaction_SpendingLimitsConstraintModule_AddTimelock> {
  /**
   * @generated from field: google.protobuf.Duration period_length = 1;
   */
  periodLength?: Duration;

  /**
   * @generated from field: uint64 amount_allowed = 2;
   */
  amountAllowed: bigint;

  constructor(data?: PartialMessage<Transaction_SpendingLimitsConstraintModule_AddTimelock>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.SpendingLimitsConstraintModule.AddTimelock";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_SpendingLimitsConstraintModule_AddTimelock;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_SpendingLimitsConstraintModule_AddTimelock;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_SpendingLimitsConstraintModule_AddTimelock;

  static equals(a: Transaction_SpendingLimitsConstraintModule_AddTimelock | PlainMessage<Transaction_SpendingLimitsConstraintModule_AddTimelock> | undefined, b: Transaction_SpendingLimitsConstraintModule_AddTimelock | PlainMessage<Transaction_SpendingLimitsConstraintModule_AddTimelock> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.SpendingLimitsConstraintModule.SetTimelock
 */
export declare class Transaction_SpendingLimitsConstraintModule_SetTimelock extends Message<Transaction_SpendingLimitsConstraintModule_SetTimelock> {
  /**
   * @generated from field: uint64 index = 1;
   */
  index: bigint;

  /**
   * @generated from field: google.protobuf.Duration period_length = 2;
   */
  periodLength?: Duration;

  /**
   * @generated from field: uint64 amount_allowed = 3;
   */
  amountAllowed: bigint;

  constructor(data?: PartialMessage<Transaction_SpendingLimitsConstraintModule_SetTimelock>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.SpendingLimitsConstraintModule.SetTimelock";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_SpendingLimitsConstraintModule_SetTimelock;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_SpendingLimitsConstraintModule_SetTimelock;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_SpendingLimitsConstraintModule_SetTimelock;

  static equals(a: Transaction_SpendingLimitsConstraintModule_SetTimelock | PlainMessage<Transaction_SpendingLimitsConstraintModule_SetTimelock> | undefined, b: Transaction_SpendingLimitsConstraintModule_SetTimelock | PlainMessage<Transaction_SpendingLimitsConstraintModule_SetTimelock> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.SpendingLimitsConstraintModule.DeleteTimelock
 */
export declare class Transaction_SpendingLimitsConstraintModule_DeleteTimelock extends Message<Transaction_SpendingLimitsConstraintModule_DeleteTimelock> {
  /**
   * @generated from field: uint64 index = 1;
   */
  index: bigint;

  constructor(data?: PartialMessage<Transaction_SpendingLimitsConstraintModule_DeleteTimelock>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.SpendingLimitsConstraintModule.DeleteTimelock";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_SpendingLimitsConstraintModule_DeleteTimelock;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_SpendingLimitsConstraintModule_DeleteTimelock;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_SpendingLimitsConstraintModule_DeleteTimelock;

  static equals(a: Transaction_SpendingLimitsConstraintModule_DeleteTimelock | PlainMessage<Transaction_SpendingLimitsConstraintModule_DeleteTimelock> | undefined, b: Transaction_SpendingLimitsConstraintModule_DeleteTimelock | PlainMessage<Transaction_SpendingLimitsConstraintModule_DeleteTimelock> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.TimeLockConstraintModule
 */
export declare class Transaction_TimeLockConstraintModule extends Message<Transaction_TimeLockConstraintModule> {
  constructor(data?: PartialMessage<Transaction_TimeLockConstraintModule>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.TimeLockConstraintModule";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_TimeLockConstraintModule;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_TimeLockConstraintModule;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_TimeLockConstraintModule;

  static equals(a: Transaction_TimeLockConstraintModule | PlainMessage<Transaction_TimeLockConstraintModule> | undefined, b: Transaction_TimeLockConstraintModule | PlainMessage<Transaction_TimeLockConstraintModule> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.TimeLockConstraintModule.DeployTimeLockConstraintModule
 */
export declare class Transaction_TimeLockConstraintModule_DeployTimeLockConstraintModule extends Message<Transaction_TimeLockConstraintModule_DeployTimeLockConstraintModule> {
  /**
   * @generated from field: string token_address = 1;
   */
  tokenAddress: string;

  constructor(data?: PartialMessage<Transaction_TimeLockConstraintModule_DeployTimeLockConstraintModule>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.TimeLockConstraintModule.DeployTimeLockConstraintModule";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_TimeLockConstraintModule_DeployTimeLockConstraintModule;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_TimeLockConstraintModule_DeployTimeLockConstraintModule;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_TimeLockConstraintModule_DeployTimeLockConstraintModule;

  static equals(a: Transaction_TimeLockConstraintModule_DeployTimeLockConstraintModule | PlainMessage<Transaction_TimeLockConstraintModule_DeployTimeLockConstraintModule> | undefined, b: Transaction_TimeLockConstraintModule_DeployTimeLockConstraintModule | PlainMessage<Transaction_TimeLockConstraintModule_DeployTimeLockConstraintModule> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.TimeLockConstraintModule.EditAmountTimeLock
 */
export declare class Transaction_TimeLockConstraintModule_EditAmountTimeLock extends Message<Transaction_TimeLockConstraintModule_EditAmountTimeLock> {
  /**
   * @generated from field: string account = 1;
   */
  account: string;

  /**
   * @generated from field: google.protobuf.Timestamp time = 2;
   */
  time?: Timestamp;

  /**
   * @generated from field: uint64 amount = 3;
   */
  amount: bigint;

  constructor(data?: PartialMessage<Transaction_TimeLockConstraintModule_EditAmountTimeLock>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.TimeLockConstraintModule.EditAmountTimeLock";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_TimeLockConstraintModule_EditAmountTimeLock;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_TimeLockConstraintModule_EditAmountTimeLock;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_TimeLockConstraintModule_EditAmountTimeLock;

  static equals(a: Transaction_TimeLockConstraintModule_EditAmountTimeLock | PlainMessage<Transaction_TimeLockConstraintModule_EditAmountTimeLock> | undefined, b: Transaction_TimeLockConstraintModule_EditAmountTimeLock | PlainMessage<Transaction_TimeLockConstraintModule_EditAmountTimeLock> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.TimeLockConstraintModule.EditAccountTimeLock
 */
export declare class Transaction_TimeLockConstraintModule_EditAccountTimeLock extends Message<Transaction_TimeLockConstraintModule_EditAccountTimeLock> {
  /**
   * @generated from field: string account = 1;
   */
  account: string;

  /**
   * @generated from field: google.protobuf.Timestamp time = 2;
   */
  time?: Timestamp;

  constructor(data?: PartialMessage<Transaction_TimeLockConstraintModule_EditAccountTimeLock>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.TimeLockConstraintModule.EditAccountTimeLock";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_TimeLockConstraintModule_EditAccountTimeLock;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_TimeLockConstraintModule_EditAccountTimeLock;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_TimeLockConstraintModule_EditAccountTimeLock;

  static equals(a: Transaction_TimeLockConstraintModule_EditAccountTimeLock | PlainMessage<Transaction_TimeLockConstraintModule_EditAccountTimeLock> | undefined, b: Transaction_TimeLockConstraintModule_EditAccountTimeLock | PlainMessage<Transaction_TimeLockConstraintModule_EditAccountTimeLock> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.TimeLockConstraintModule.EditTimeLock
 */
export declare class Transaction_TimeLockConstraintModule_EditTimeLock extends Message<Transaction_TimeLockConstraintModule_EditTimeLock> {
  /**
   * @generated from field: google.protobuf.Timestamp time = 1;
   */
  time?: Timestamp;

  constructor(data?: PartialMessage<Transaction_TimeLockConstraintModule_EditTimeLock>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.TimeLockConstraintModule.EditTimeLock";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_TimeLockConstraintModule_EditTimeLock;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_TimeLockConstraintModule_EditTimeLock;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_TimeLockConstraintModule_EditTimeLock;

  static equals(a: Transaction_TimeLockConstraintModule_EditTimeLock | PlainMessage<Transaction_TimeLockConstraintModule_EditTimeLock> | undefined, b: Transaction_TimeLockConstraintModule_EditTimeLock | PlainMessage<Transaction_TimeLockConstraintModule_EditTimeLock> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.VestingPeriodConstraintModule
 */
export declare class Transaction_VestingPeriodConstraintModule extends Message<Transaction_VestingPeriodConstraintModule> {
  constructor(data?: PartialMessage<Transaction_VestingPeriodConstraintModule>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.VestingPeriodConstraintModule";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_VestingPeriodConstraintModule;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_VestingPeriodConstraintModule;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_VestingPeriodConstraintModule;

  static equals(a: Transaction_VestingPeriodConstraintModule | PlainMessage<Transaction_VestingPeriodConstraintModule> | undefined, b: Transaction_VestingPeriodConstraintModule | PlainMessage<Transaction_VestingPeriodConstraintModule> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.VestingPeriodConstraintModule.DeployVestingPeriodConstraintModule
 */
export declare class Transaction_VestingPeriodConstraintModule_DeployVestingPeriodConstraintModule extends Message<Transaction_VestingPeriodConstraintModule_DeployVestingPeriodConstraintModule> {
  /**
   * @generated from field: string token_address = 1;
   */
  tokenAddress: string;

  constructor(data?: PartialMessage<Transaction_VestingPeriodConstraintModule_DeployVestingPeriodConstraintModule>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.VestingPeriodConstraintModule.DeployVestingPeriodConstraintModule";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_VestingPeriodConstraintModule_DeployVestingPeriodConstraintModule;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_VestingPeriodConstraintModule_DeployVestingPeriodConstraintModule;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_VestingPeriodConstraintModule_DeployVestingPeriodConstraintModule;

  static equals(a: Transaction_VestingPeriodConstraintModule_DeployVestingPeriodConstraintModule | PlainMessage<Transaction_VestingPeriodConstraintModule_DeployVestingPeriodConstraintModule> | undefined, b: Transaction_VestingPeriodConstraintModule_DeployVestingPeriodConstraintModule | PlainMessage<Transaction_VestingPeriodConstraintModule_DeployVestingPeriodConstraintModule> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.VestingPeriodConstraintModule.SetVestingOptions
 */
export declare class Transaction_VestingPeriodConstraintModule_SetVestingOptions extends Message<Transaction_VestingPeriodConstraintModule_SetVestingOptions> {
  /**
   * @generated from field: google.protobuf.Timestamp vesting_start = 1;
   */
  vestingStart?: Timestamp;

  /**
   * @generated from field: uint64 vested_fraction_after_start = 2;
   */
  vestedFractionAfterStart: bigint;

  /**
   * @generated from field: uint64 vesting_ratio = 3;
   */
  vestingRatio: bigint;

  constructor(data?: PartialMessage<Transaction_VestingPeriodConstraintModule_SetVestingOptions>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.VestingPeriodConstraintModule.SetVestingOptions";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_VestingPeriodConstraintModule_SetVestingOptions;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_VestingPeriodConstraintModule_SetVestingOptions;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_VestingPeriodConstraintModule_SetVestingOptions;

  static equals(a: Transaction_VestingPeriodConstraintModule_SetVestingOptions | PlainMessage<Transaction_VestingPeriodConstraintModule_SetVestingOptions> | undefined, b: Transaction_VestingPeriodConstraintModule_SetVestingOptions | PlainMessage<Transaction_VestingPeriodConstraintModule_SetVestingOptions> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.WhitelistConstraintModule
 */
export declare class Transaction_WhitelistConstraintModule extends Message<Transaction_WhitelistConstraintModule> {
  constructor(data?: PartialMessage<Transaction_WhitelistConstraintModule>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.WhitelistConstraintModule";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_WhitelistConstraintModule;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_WhitelistConstraintModule;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_WhitelistConstraintModule;

  static equals(a: Transaction_WhitelistConstraintModule | PlainMessage<Transaction_WhitelistConstraintModule> | undefined, b: Transaction_WhitelistConstraintModule | PlainMessage<Transaction_WhitelistConstraintModule> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.WhitelistConstraintModule.DeployWhitelistConstraintModule
 */
export declare class Transaction_WhitelistConstraintModule_DeployWhitelistConstraintModule extends Message<Transaction_WhitelistConstraintModule_DeployWhitelistConstraintModule> {
  /**
   * @generated from field: string token_address = 1;
   */
  tokenAddress: string;

  constructor(data?: PartialMessage<Transaction_WhitelistConstraintModule_DeployWhitelistConstraintModule>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.WhitelistConstraintModule.DeployWhitelistConstraintModule";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_WhitelistConstraintModule_DeployWhitelistConstraintModule;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_WhitelistConstraintModule_DeployWhitelistConstraintModule;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_WhitelistConstraintModule_DeployWhitelistConstraintModule;

  static equals(a: Transaction_WhitelistConstraintModule_DeployWhitelistConstraintModule | PlainMessage<Transaction_WhitelistConstraintModule_DeployWhitelistConstraintModule> | undefined, b: Transaction_WhitelistConstraintModule_DeployWhitelistConstraintModule | PlainMessage<Transaction_WhitelistConstraintModule_DeployWhitelistConstraintModule> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.WhitelistConstraintModule.EditWhitelist
 */
export declare class Transaction_WhitelistConstraintModule_EditWhitelist extends Message<Transaction_WhitelistConstraintModule_EditWhitelist> {
  /**
   * @generated from field: string account = 1;
   */
  account: string;

  /**
   * @generated from field: bool whitelisted = 2;
   */
  whitelisted: boolean;

  constructor(data?: PartialMessage<Transaction_WhitelistConstraintModule_EditWhitelist>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.WhitelistConstraintModule.EditWhitelist";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_WhitelistConstraintModule_EditWhitelist;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_WhitelistConstraintModule_EditWhitelist;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_WhitelistConstraintModule_EditWhitelist;

  static equals(a: Transaction_WhitelistConstraintModule_EditWhitelist | PlainMessage<Transaction_WhitelistConstraintModule_EditWhitelist> | undefined, b: Transaction_WhitelistConstraintModule_EditWhitelist | PlainMessage<Transaction_WhitelistConstraintModule_EditWhitelist> | undefined): boolean;
}

/**
 * @generated from message transaction.v1.Transaction.WhitelistConstraintModule.BulkEditWhitelist
 */
export declare class Transaction_WhitelistConstraintModule_BulkEditWhitelist extends Message<Transaction_WhitelistConstraintModule_BulkEditWhitelist> {
  /**
   * @generated from field: repeated string accounts = 1;
   */
  accounts: string[];

  /**
   * @generated from field: bool whitelisted = 2;
   */
  whitelisted: boolean;

  constructor(data?: PartialMessage<Transaction_WhitelistConstraintModule_BulkEditWhitelist>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.WhitelistConstraintModule.BulkEditWhitelist";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_WhitelistConstraintModule_BulkEditWhitelist;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_WhitelistConstraintModule_BulkEditWhitelist;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_WhitelistConstraintModule_BulkEditWhitelist;

  static equals(a: Transaction_WhitelistConstraintModule_BulkEditWhitelist | PlainMessage<Transaction_WhitelistConstraintModule_BulkEditWhitelist> | undefined, b: Transaction_WhitelistConstraintModule_BulkEditWhitelist | PlainMessage<Transaction_WhitelistConstraintModule_BulkEditWhitelist> | undefined): boolean;
}

/**
 * Metadata 
 *
 * @generated from message transaction.v1.Transaction.Metadata
 */
export declare class Transaction_Metadata extends Message<Transaction_Metadata> {
  /**
   * @generated from field: string hash = 1;
   */
  hash: string;

  /**
   * @generated from field: google.protobuf.Timestamp date = 2;
   */
  date?: Timestamp;

  /**
   * @generated from field: string reverted = 3;
   */
  reverted: string;

  constructor(data?: PartialMessage<Transaction_Metadata>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "transaction.v1.Transaction.Metadata";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Transaction_Metadata;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Transaction_Metadata;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Transaction_Metadata;

  static equals(a: Transaction_Metadata | PlainMessage<Transaction_Metadata> | undefined, b: Transaction_Metadata | PlainMessage<Transaction_Metadata> | undefined): boolean;
}

